---
title: "The Pond Question"
author: "Anonymous"
date: "April 13, 2021"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Header 1

## Header 2

### The pond question

Now, we plan.

```{r}
## x is the days
x <- 1:10

## initial area
area1 <- 1/100

## y is the area of the pond
y <- 2^(x-1) * area1
```

Now, we plot.

```{r echo=TRUE}
plot(x, y, xlab="Days", ylab="Area covered by water lilys")
```



## Playing with Functions

```{r}
randsamp <- function(n, d="uniform") {

  if(d == "uniform") {
    ret <- runif(n)
  } else if(d == "normal") {
    ret <- rnorm(n)
  } else if(d == "binomial") {
    ret <- rbinom(n, size=1, prob=0.5)
  } else {
    stop("I don't know this distribution!")
  }

  return(ret)
}
```

v <- c("ANKRD22", "ank.rep.domain 12", "ifng-1", "ANKRD-33", "  ankrd23")
v
gsub("^ *ank.*", "ANKRD", v)
gsub("^ *ank.*", "ANKRD", v, ignore.case = T)
gsub("^ *ank[a-zA-Z-. ]*", "ANKRD", v, ignore.case = T)
gsub("^ *ank[a-zA-Z. -]*", "ANKRD", v, ignore.case = T)
gsub("^ *ank[^0-9]*", "ANKRD", v, ignore.case = T)

